# Restaurante_ICE/dockerfiles/Dockerfile.client-admin

FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@9 --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

ENV VITE_AUTH_URL=http://localhost:5227/api/v1
ENV VITE_API_URL=http://localhost:3021/RestauranteICE/v1
ENV VITE_ADMIN_URL=http://localhost:3021/RestauranteICE/v1

EXPOSE 5173

CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]