# Restaurante_ICE/dockerfiles/Dockerfile.server-admin

FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.30.0 --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

ENV PORT=3021
ENV URI_MONGODB=mongodb://localhost:27017/restICE
ENV CLOUDINARY_CLOUD_NAME=dss7fs6pl
ENV CLOUDINARY_API_KEY=576915661566217
ENV CLOUDINARY_API_SECRET=d5QSRBAe6VUFv2zb3oTU6NueJ3g
ENV JWT_SECRET=ThisIs$$ecretKeyForR3$$t@urant1234
ENV JWT_EXPIRES_IN=1h
ENV JWT_ISSUER=AuthService
ENV JWT_AUDIENCE=AuthServiceUsers
ENV NODE_TLS_REJECT_UNAUTHORIZED=0

EXPOSE 3021

CMD ["pnpm", "run", "dev"]